[package]
name = "image_annealing_cli"
version = "0.1.0"
authors = ["Bernard Llanos"]
edition = "2018"
description = "Command-line utilities library for the image_annealing crate"
keywords = ["image","graphics","cli"]
license = "MIT OR Apache-2.0"

[dependencies]
image_annealing = { path = "../image_annealing" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
test_utils = { path = "../test_utils" }