[package]
name = "image_annealing_cli"
version = "0.1.0"
authors = ["Bernard Llanos"]
edition = "2021"
description = "Command-line utilities library for the image_annealing crate"
keywords = ["image","graphics","cli"]
license = "MIT OR Apache-2.0"

[dependencies]
futures = "0.3.21"
image_annealing = { path = "../image_annealing" }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"

[dev-dependencies]
async-trait = "0.1.56"
test_utils = { path = "../test_utils" }