[workspace]
members = [
    "image_annealing",
    "image_annealing_cli",
    "image_annealing_cli_bin",
    "image_annealing_shader",
    "image_annealing_shader_cli",
    "test_util",
]
resolver = "2"