[package]
name = "image_annealing"
version = "0.1.0"
authors = ["Bernard Llanos <bernard@mojow.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
