[package]
name = "test_utils"
version = "0.1.0"
authors = ["Bernard Llanos"]
edition = "2018"
description = "Test helper utilities for the workspace"
license = "MIT OR Apache-2.0"

[dependencies]
image = "0.23.14"
image_annealing = { path = "../image_annealing" }