[package]
name = "image_annealing"
version = "0.1.0"
authors = ["Bernard Llanos"]
edition = "2018"
description = "Approximate optimization algorithms applied to images"
keywords = ["image","graphics"]
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "1.3.2"
bytemuck = { version = "1.9.1", features = [ "derive" ] }
futures = "0.3.21"
image = "0.24.2"
image_annealing_shaders = { path = "../image_annealing_shaders" }
wgpu = "0.12.0"

[build-dependencies]
image_annealing_shaders = { path = "../image_annealing_shaders" }

[dev-dependencies]
test_utils = { path = "../test_utils" }