[package]
name = "image_annealing"
version = "0.1.0"
authors = ["Bernard Llanos"]
edition = "2018"
description = "Approximate optimization algorithms applied to images"
keywords = ["image","graphics"]
license = "MIT OR Apache-2.0"

[dependencies]
bytemuck = "1.5"
futures = "0.3"
image = "0.23"
image_annealing_shaders = { path = "../image_annealing_shaders" }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git" }

[build-dependencies]
image_annealing_shaders = { path = "../image_annealing_shaders" }

[dev-dependencies]
test_utils = { path = "../test_utils" }