[package]
name = "image_annealing"
version = "0.1.0"
authors = ["Bernard Llanos"]
edition = "2018"
description = "Approximate optimization algorithms applied to images"
keywords = ["image","graphics"]
license = "MIT OR Apache-2.0"

[dependencies]
bytemuck = "1.4"
futures = "0.3"
image = "0.23"
image_annealing_build_utils = { path = "../image_annealing_build_utils" }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git" }

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
image_annealing_build_utils = { path = "../image_annealing_build_utils" }
rayon = "1.5"
shaderc = "0.7"